"""normalize parent child relationship of posts

Revision ID: 380b2fe6e810
Revises: 73f343883cef
Create Date: 2020-11-21 12:09:22.776911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '380b2fe6e810'
down_revision = '73f343883cef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent_child_post',
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('child_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['post.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parent_child_post')
    # ### end Alembic commands ###
