"""Added label column to post table

Revision ID: 4fd0f5e6bd16
Revises: 505319bada06
Create Date: 2020-10-27 14:41:36.378121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fd0f5e6bd16'
down_revision = '505319bada06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('label', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'label')
    # ### end Alembic commands ###
