"""Index parent_ids column for post table

Revision ID: 73f343883cef
Revises: 4fd0f5e6bd16
Create Date: 2020-11-12 14:34:12.447234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73f343883cef'
down_revision = '4fd0f5e6bd16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_post_parent_ids'), 'post', ['parent_ids'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_parent_ids'), table_name='post')
    # ### end Alembic commands ###
